name: python-tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

  test:
    runs-on: ubuntu-latest
    needs: build  # ensures test runs after build
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest (single file)
        run: |
          pytest -q test_sample.py

  deploy:
    runs-on: ubuntu-latest
    needs: test  # ← this runs *after* test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deploy step
        run: echo "Deploying project..."